version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-04-20T17-56-55Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_COMPRESSION_ENABLE: "on"
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: abc223456789
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./volumes/data1-1:/data1
      - ./volumes/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./volumes/data2-1:/data1
      - ./volumes/data2-2:/data2

  nginx:
    image: nginx:latest
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
# avoid collision with class B uni private network
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.8.0.0/24

